### ISSUE TITLE
[Ques/Bug]: Activity Matrix generation and reduction of tests

### ISSUE THREAD

**Issue by Enkryp** [PRAISE-group/Chiron-Framework#6]
### What happened?

Activity Matrix is generated in the following lines in sbfl.py:
```
original_tests = sbfl_object.generateTests(inputVars=inputVars, total_tests=Ntests)
oracle = FaultOrcale(irhandler1, irhandler2, original_tests)
ActivityMatrix = sbfl_object.generateSpectrum(oracle)
```

In generateSpectrum:
```
if ir1_trltl_pos == ir2_trltl_pos:
spectrum[i, -1] = 0 # test-case passes.
else:
spectrum[i, -1] = 1 # test-case fails.
```

Last index is always set to 0/1. 
Further, in the following:

```
best_individual = pop[0].individual

 reduced_tests = []
 for tests in best_individual:
   reduced_tests.append(original_tests[tests[-1]])
```

tests[-1] is either 0 or 1. reduced_tests is just a list of duplicate
copies of first 2 original_tests.

Maybe there is a bug: generateActivityMatrix is defined but never used anywhere in the codebase, is it what was intended to call ?

Affected version: 1.0.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vishalsng112** [comment]
Yes, you're correct, and we appreciate your keen observation. The code is indeed calling the wrong function, and this is a bug. We will address this issue and ensure it's fixed in our next release.

**Comment by lahiri-phdworks** [comment]
@Enkryp I guess this has been fixed now. https://github.com/PRAISE-group/Chiron-Framework/commit/e1c40726887177a9e54a51610f22a5495b5554df

Thanks @Vishalsng112 @Enkryp
