### ISSUE TITLE
[Bug/Enhance]: Loop fails to terminate when loop argument is negative. 

### ISSUE THREAD

**Issue by Enkryp** [PRAISE-group/Chiron-Framework#7]
## Bug
Infinite loops for repeat (negative) [...]

## Fix 
In   visitLoop in builder.py: 

change 
```loopCond = ChironAST.ConditionCommand(ChironAST.NEQ(counterVar, constZero))```
to 
```loopCond = ChironAST.ConditionCommand(ChironAST.GT(counterVar, constZero))```

otherwise fuzzers will go into infinite loops if repeat has a fuzzing var.

version: 1.0.4

**Comment by lahiri-phdworks** [comment]
@Enkryp This would change the semantics of the way we handle loops; if you check the IR for loops, we need the loop variable to be positive since we perform a decrement. Example below, the `__rep_counter_3` must be 0 or greater, since we just want to loop through, we don't support conditional loops yet. 

```
[L17] :__rep_counter_3 = 5 [1]
[L18] (:__rep_counter_3 != 0) [5]
[L19] forward :p [1]
[L20] left 72 [1]
[L21] :__rep_counter_3 = (:__rep_counter_3 - 1) [1]
```

**Comment by lahiri-phdworks** [comment]
However, `GTE` may work fine I guess.

**Comment by Enkryp** [comment]
> @Enkryp This would change the semantics of the way we handle loops; if you check the IR for loops, we need the loop variable to be positive since we perform a decrement. Example below, the `__rep_counter_3` must be 0 or greater, since we just want to loop through, we don't support conditional loops yet.
> 
> ```
> [L17] :__rep_counter_3 = 5 [1]
> [L18] (:__rep_counter_3 != 0) [5]
> [L19] forward :p [1]
> [L20] left 72 [1]
> [L21] :__rep_counter_3 = (:__rep_counter_3 - 1) [1]
> ```

What I meant was if there is a statement :
```repeat x [
...
]```
and this is passed to fuzzer, fuzzer might try to check this of x = -1 say, that will never terminate.

**Comment by lahiri-phdworks** [comment]
Yeah, so we will change to `greater than equal`, for x = -1, we won't even enter the loop 

```
x = -1
if (x >= 0) {
....
....
x = x - 1;
}
```

**Comment by lahiri-phdworks** [comment]
We shall fix it in the next release. Thanks @Enkryp

**Comment by Enkryp** [comment]
> Yeah, so we will change to `greater than equal`, for x = -1, we won't even enter the loop
> 
> ```
> x = -1
> if (x >= 0) {
> ....
> ....
> x = x - 1;
> }
> ```

shouldn't it be greater than ? if x = 0 we still dont want to enter.

**Comment by lahiri-phdworks** [comment]
I see. You are right here.

**Comment by lahiri-phdworks** [comment]
@Enkryp This has now been fixed. Thanks!
