### ISSUE TITLE
[Bug] Issue in abstractInterpretation.py for edge label check. 

### ISSUE THREAD

**Issue by Enkryp** [PRAISE-group/Chiron-Framework#8]
**Describe the bug**
I think line 112 should be :
```
                    if label != 'Cond_False':

```
in 
```
            inlist = []
            for pred in predList:
                label = cfg.get_edge_label(pred, currBB)
                if bbOut[pred.name]:
                    if label == 'T':
                        inlist.append(bbOut[pred.name][0])
                    else:
                        assert len(bbOut[pred.name]) > 1
                        inlist.append(bbOut[pred.name][1])

```

Probably a refactoring bug. 

https://github.com/PRAISE-group/Chiron-Framework/blob/9a3d2c29ccb13b36ac306893cce13a9c4b81921a/ChironCore/abstractInterpretation.py#L112

**Comment by skmuduli92** [comment]
I think here were tracking the label of the branch from one of its predicessor to current basic-block. 

In the figure below consider the node L4. It recieves input from L1, L2 & L3. T & F label on edges simply indicates whether current block is reachable from either True or False branch of its predecessor. 

![x](https://github.com/PRAISE-group/Chiron-Framework/assets/1248868/4f5f38e8-775a-4cde-b0bf-4bef9be89080)

**Comment by lahiri-phdworks** [comment]
@Enkryp Yeah you are right. Will fix it and make a push.

**Comment by lahiri-phdworks** [comment]
@Enkryp This has now been fixed. Thanks!

**Comment by Enkryp** [comment]
> @Enkryp This has now been fixed. Thanks!
@lahiri-phdworks 
It can be 'flow_edge' as well. So I think it's still not fixed.

**Comment by lahiri-phdworks** [comment]
@Enkryp Can you check now?

**Comment by Enkryp** [comment]
> @Enkryp Can you check now?

Yes, now it's fine
